<?php
session_start();
if($_SESSION['nicolalawrence_admin']['admin_login']!=md5($_SESSION['nicolalawrence_admin']['admin_password'].session_id()))
{
	header("location:index.php");
	exit;
}
$myroot="../../";
include_once($myroot."config/config.php");
$cat->addFeaturedCategory();
	$parent_id=0;
	$row_cats=$cat->showFeaturedCategories($parent_id);
?>