<?php
session_start();
if($_SESSION['nicolalawrence_admin']['admin_login']!=md5($_SESSION['nicolalawrence_admin']['admin_password'].session_id()))
{
	header("location:index.php");
	exit;
}
$myroot="../../";
include_once($myroot."config/config.php");
$finish_specific_group_id=$_POST['id'];
$finishes->deleteFinishSpecificGroup($finish_specific_group_id);
?>